#ifndef GUARD_CONFIG_LEVEL_SCALING_H
#define GUARD_CONFIG_LEVEL_SCALING_H

#define B_LEVEL_SCALING_ENABLED         TRUE

// Trainer defaults
#define B_TRAINER_SCALING_ENABLED             TRUE
#define B_TRAINER_SCALING_DEFAULT_MODE        LEVEL_SCALING_PARTY_HIGHEST
#define B_TRAINER_SCALING_LEVEL_AUGMENT       2
#define B_TRAINER_SCALING_LEVEL_VARIATION_PCT 0
#define B_TRAINER_SCALING_MIN_LEVEL           0
#define B_TRAINER_SCALING_MAX_LEVEL           0
#define B_TRAINER_SCALING_MANAGE_EVOLUTIONS   TRUE
#define B_TRAINER_SCALING_EXCLUDE_FAINTED     FALSE
#define B_TRAINER_SCALING_SCALE_EVS           TRUE
#define B_TRAINER_SCALING_SCALE_MOVES         TRUE
#define B_TRAINER_SCALING_SCALE_ITEMS         ITEM_NONE

// Shared progression tiers
#define B_SCALING_TIER_MID_MIN_LEVEL        20
#define B_SCALING_TIER_LATE_MIN_LEVEL       40
#define B_SCALING_TIER_ENDGAME_MIN_LEVEL    100

// Party-size scaling
#define B_TRAINER_PARTY_SIZE_MODE  PARTY_SIZE_SCALING_NORMAL
#define B_TRAINER_PARTY_SIZE_SORT  PARTY_SIZE_SORT_NONE
#define B_TRAINER_PARTY_ACE_EXEMPT      TRUE

// BST ceilings per tier
#define B_SCALING_BST_BELOW_MID         400
#define B_SCALING_BST_MID               540
#define B_SCALING_BST_LATE              999
#define B_SCALING_BST_ABOVE_ENDGAME     999

// Wild defaults
#define B_WILD_SCALING_ENABLED              TRUE
#define B_WILD_SCALING_DEFAULT_MODE         LEVEL_SCALING_PARTY_AVG
#define B_WILD_SCALING_LEVEL_AUGMENT        -3
#define B_WILD_SCALING_LEVEL_VARIATION_PCT  0
#define B_WILD_SCALING_MIN_LEVEL            0
#define B_WILD_SCALING_MAX_LEVEL            0
#define B_WILD_SCALING_MANAGE_EVOLUTIONS    TRUE
#define B_WILD_SCALING_EXCLUDE_FAINTED      FALSE

// Evolution system
#define B_SCALING_USE_OVERRIDES         TRUE
#define B_SCALING_DEBUG_PRINT           FALSE

#endif // GUARD_CONFIG_LEVEL_SCALING_H